.TH DYNAMIC-CLI "1" "November 2016" "dynamic-cli 1.0"
.SH NAME
dynamic-cli \- a remote procedure call client for Dynamic Core. 
.SH SYNOPSIS
dynamic-cli [options] <command> [params] \- Send command to Dynamic Core. 
.TP
dynamic-cli [options] help \- Asks Dynamic Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the dynamic-cli program. dynamic-cli is an RPC client used to send commands to Dynamic Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
